CREATE TABLE SETTLEMENTS (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
    SNAME varchar(23));
CREATE TABLE STREETS (
    PAK INTEGER PRIMARY KEY CONSTRAINT PAK_CH CHECK(PAK < 10000000),
    SNAME VARCHAR(47) NOT NULL,
    SETTLEMENT_ID INTEGER,
    CONSTRAINT SET_ID_FK
    FOREIGN KEY (SETTLEMENT_ID)
    REFERENCES SETTLEMENTS (ID));
CREATE TABLE LOCATIONS (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
    X FLOAT DEFAULT 0,
    Y FLOAT DEFAULT 0,
    CODE VARCHAR(10) DEFAULT NULL,
    STREET_PAK INTEGER,
    NOTE VARCHAR(1024) DEFAULT NULL,
    CONSTRAINT SPAK_FK
    FOREIGN KEY(STREET_PAK)
    REFERENCES STREETS(PAK));
CREATE TABLE RECIPIENTS (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
    RNAME VARCHAR(51) NOT NULL,
    LOCATION_ID INTEGER,
    REG_NO BIGINT DEFAULT NULL,
    IS_RETIREE BOOLEAN DEFAULT FALSE,
    CONSTRAINT LOC_FK
    FOREIGN KEY(LOCATION_ID)
    REFERENCES LOCATIONS(ID));
CREATE INDEX RNAME_IND on RECIPIENTS(RNAME)